<a href="https://colab.research.google.com/github/Rohithtechis/Health-insurance-pred/blob/main/Health_insurance_pred.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [279]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
sns.set(style='white', color_codes=True)

In [280]:
df=pd.read_csv('/content/train_Df64byy.csv')
df.head()

ID City_Code  Region_Code  ... Reco_Policy_Cat Reco_Policy_Premium  Response
0   1        C3         3213  ...              22             11628.0         0
1   2        C5         1117  ...              22             30510.0         0
2   3        C5         3732  ...              19              7450.0         1
3   4       C24         4378  ...              19             17780.0         0
4   5        C8         2190  ...              16             10404.0         0

[5 rows x 14 columns]

In [281]:
df.shape

(50882, 14)

In [282]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50882 entries, 0 to 50881
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   ID                       50882 non-null  int64  
 1   City_Code                50882 non-null  object 
 2   Region_Code              50882 non-null  int64  
 3   Accomodation_Type        50882 non-null  object 
 4   Reco_Insurance_Type      50882 non-null  object 
 5   Upper_Age                50882 non-null  int64  
 6   Lower_Age                50882 non-null  int64  
 7   Is_Spouse                50882 non-null  object 
 8   Health Indicator         39191 non-null  object 
 9   Holding_Policy_Duration  30631 non-null  object 
 10  Holding_Policy_Type      30631 non-null  float64
 11  Reco_Policy_Cat          50882 non-null  int64  
 12  Reco_Policy_Premium      50882 non-null  float64
 13  Response                 50882 non-null  int64  
dtypes: float64(2), int64(6

In [283]:
df.isna().sum()

ID                             0
City_Code                      0
Region_Code                    0
Accomodation_Type              0
Reco_Insurance_Type            0
Upper_Age                      0
Lower_Age                      0
Is_Spouse                      0
Health Indicator           11691
Holding_Policy_Duration    20251
Holding_Policy_Type        20251
Reco_Policy_Cat                0
Reco_Policy_Premium            0
Response                       0
dtype: int64

In [284]:
df['Health Indicator'].value_counts()

X1    13010
X2    10332
X3     6762
X4     5743
X5     1727
X6     1280
X7      196
X8       78
X9       63
Name: Health Indicator, dtype: int64

In [285]:
df['Reco_Policy_Cat'].mean()

15.115188082229473

In [286]:
df["Health Indicator"].fillna('X1', inplace = True)

In [287]:
df["Holding_Policy_Duration"].fillna('14+' , inplace = True)
df["Reco_Policy_Cat"].fillna(15.11, inplace = True)

In [288]:
df.isna().sum()

ID                             0
City_Code                      0
Region_Code                    0
Accomodation_Type              0
Reco_Insurance_Type            0
Upper_Age                      0
Lower_Age                      0
Is_Spouse                      0
Health Indicator               0
Holding_Policy_Duration        0
Holding_Policy_Type        20251
Reco_Policy_Cat                0
Reco_Policy_Premium            0
Response                       0
dtype: int64

In [289]:
df=df.drop(['Holding_Policy_Type'],axis=1)

In [290]:
df.select_dtypes(include='object')

City_Code Accomodation_Type  ... Health Indicator Holding_Policy_Duration
0            C3            Rented  ...               X1                     14+
1            C5             Owned  ...               X2                     14+
2            C5             Owned  ...               X1                     1.0
3           C24             Owned  ...               X1                     14+
4            C8            Rented  ...               X2                     3.0
...         ...               ...  ...              ...                     ...
50877        C4            Rented  ...               X3                     14+
50878        C5            Rented  ...               X3                     7.0
50879        C1            Rented  ...               X2                     14+
50880        C1             Owned  ...               X2                     2.0
50881        C3            Rented  ...               X3                     2.0

[50882 rows x 6 columns]

In [291]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50882 entries, 0 to 50881
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   ID                       50882 non-null  int64  
 1   City_Code                50882 non-null  object 
 2   Region_Code              50882 non-null  int64  
 3   Accomodation_Type        50882 non-null  object 
 4   Reco_Insurance_Type      50882 non-null  object 
 5   Upper_Age                50882 non-null  int64  
 6   Lower_Age                50882 non-null  int64  
 7   Is_Spouse                50882 non-null  object 
 8   Health Indicator         50882 non-null  object 
 9   Holding_Policy_Duration  50882 non-null  object 
 10  Reco_Policy_Cat          50882 non-null  int64  
 11  Reco_Policy_Premium      50882 non-null  float64
 12  Response                 50882 non-null  int64  
dtypes: float64(1), int64(6), object(6)
memory usage: 5.0+ MB


In [292]:
from sklearn.preprocessing import OneHotEncoder
en = OneHotEncoder()
df['City_Code']=en.fit_transform(df['City_Code'].values.reshape(-1,1)).toarray()
df['Accomodation_Type']=en.fit_transform(df['Accomodation_Type'].values.reshape(-1,1)).toarray()
df['Reco_Insurance_Type']=en.fit_transform(df['Reco_Insurance_Type'].values.reshape(-1,1)).toarray()
df['Is_Spouse']=en.fit_transform(df['Is_Spouse'].values.reshape(-1,1)).toarray()
df['Health Indicator']=en.fit_transform(df['Health Indicator'].values.reshape(-1,1)).toarray()
df['Holding_Policy_Duration']=en.fit_transform(df['Holding_Policy_Duration'].values.reshape(-1,1)).toarray()

In [293]:
df.head()

ID  City_Code  Region_Code  ...  Reco_Policy_Cat  Reco_Policy_Premium  Response
0   1        0.0         3213  ...               22              11628.0         0
1   2        0.0         1117  ...               22              30510.0         0
2   3        0.0         3732  ...               19               7450.0         1
3   4        0.0         4378  ...               19              17780.0         0
4   5        0.0         2190  ...               16              10404.0         0

[5 rows x 13 columns]

In [294]:
from sklearn.preprocessing import StandardScaler
# Initialise the Scaler
scaler = StandardScaler()
  
# To scale data
scaler.fit(df)
from sklearn.preprocessing import normalize
normalize(df)

array([[8.28921759e-05, 0.00000000e+00, 2.66332561e-01, ...,
        1.82362787e-03, 9.63870221e-01, 0.00000000e+00],
       [6.55081583e-05, 0.00000000e+00, 3.65863064e-02, ...,
        7.20589741e-04, 9.99326955e-01, 0.00000000e+00],
       [3.60030321e-04, 0.00000000e+00, 4.47877719e-01, ...,
        2.28019203e-03, 8.94075297e-01, 1.20010107e-04],
       ...,
       [9.75876270e-01, 1.91799581e-05, 8.47754149e-03, ...,
        2.30159498e-04, 2.18152844e-01, 0.00000000e+00],
       [8.74797981e-01, 1.71930186e-05, 6.87720746e-05, ...,
        2.75088298e-04, 4.84485511e-01, 1.71930186e-05],
       [9.73039610e-01, 0.00000000e+00, 7.39312750e-02, ...,
        3.44222180e-04, 2.18466344e-01, 0.00000000e+00]])

In [295]:
from sklearn.model_selection import train_test_split
train, test=train_test_split(df,test_size=0.25)

In [296]:
X_train=train.drop(['Response'],axis=1)
y_train=train['Response']
X_test=test.drop(['Response'],axis=1)
y_test=test['Response']

In [297]:
print('Dimension of X_train dataframe:',X_train.shape)
print('Dimension of y_train dataframe:',y_train.shape)
print('Dimension of X_test dataframe:',X_test.shape)
print('Dimension of y_test dataframe:',y_test.shape)

Dimension of X_train dataframe: (38161, 12)
Dimension of y_train dataframe: (38161,)
Dimension of X_test dataframe: (12721, 12)
Dimension of y_test dataframe: (12721,)


In [298]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(X_train,y_train)
y_pred=model.predict(X_test)
LR=model.score(X_test,y_test)
LR

0.7617325681943243

In [299]:
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
from sklearn.metrics import confusion_matrix
rfcl = RandomForestClassifier(criterion = 'entropy', class_weight={0:.5,1:.5}, max_depth = 5, min_samples_leaf=5)
rfcl = rfcl.fit(X_train, y_train)
test_pred = rfcl.predict(X_test)
rfcl_score=rfcl.score(X_test , y_test)
print("The Random forest model accuracy is {}".format(rfcl_score))
print("The confusion matrix of Random Forest Model is")
print(metrics.confusion_matrix(y_test,test_pred))

The Random forest model accuracy is 0.7617325681943243
The confusion matrix of Random Forest Model is
[[9690    0]
 [3031    0]]


In [300]:
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier(random_state=0,max_depth=3)
clf.fit(X_train, y_train)
pred = clf.predict(X_test)
pred
#validation of built model
from sklearn.metrics import accuracy_score

print('The accuracy of the Decision Tree is {}%'.format(round(accuracy_score(pred,y_test)*100,2)))

The accuracy of the Decision Tree is 76.13%


In [301]:
import xgboost as xgb
from xgboost import XGBClassifier
from xgboost import plot_importance
xgbl=XGBClassifier()
xgbl.fit(X_train,y_train)
test_pred=xgbl.predict(X_test)
xgbl_score=xgbl.score(X_test,y_test)
print("The XGBoostclassifier model accuracy is {}".format(xgbl_score))
print("The confusion matrix of XGBoostclassifier model is")
print(metrics.confusion_matrix(y_test,test_pred))

The XGBoostclassifier model accuracy is 0.7616539580221681
The confusion matrix of XGBoostclassifier model is
[[9686    4]
 [3028    3]]
